version: '3'
services:
    strelkabot:
        container_name: strelkabot
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
          - db
        ports:
          - 8080:8000
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: strelkabot